quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=student2026
quarkus.datasource.password=student2026

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/student2026
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy = drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.rest-client.time-api.url=https://time.now/developer/api/
quarkus.rest-client.time-api.scope=jakarta.inject.Singleton


